# Name of workflow
name: Deploy to GreenOrg

# 'on' = Trigger this flow when these conditions are met (pull request made to master branch)
on:
  pull_request:
    branches:
      - master
    types:
      - closed  # Trigger only when PR is merged

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your code

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1.0.0

      - name: Authorize GreenOrg
        run: |
          sfdx force:auth:password:grant --clientid ${{ secrets.CLIENT_ID }} --clientsecret ${{ secrets.CLIENT_SECRET }} --username ${{ secrets.SF_USER }} --password ${{ secrets.SF_PASS }} --setalias greenOrg

        env:
          SFDX_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SFDX_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Deploy to GreenOrg
        run: |
            sfdx force:source:deploy -p force-app --targetusername greenOrg --wait 10 --testlevel RunLocalTests
